name: mcxtrace-winbasictest

on:
  push:
  pull_request:

jobs:
  build:
    # More platform information available on:
    # https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: cmd

    strategy:
      matrix:
#        os: [windows-2019, windows-2022]
        os: [windows-2022]

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: src

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

      #Two ways of enabling cl.exe and other tools. One is via an external action...:
    - name: Setup VS in shell
      uses: ilammy/msvc-dev-cmd@v1
      #...but a simpler one might be to simply invoke the correct vcvars64.bat
      #file first, like...:
      #
      #    - name: whatever
      #      shell: cmd
      #      run: |
      #        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      #        cl /help
      #
      #...but since we also want to support VS 2019, we use the above action for now

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: 'msmpi'

    - name: Setup MPI cygpath bash...
      shell: bash
      run:   |
        cygpath -sm "$MSMPI_INC" > includepath.txt
        cygpath -sm "$MSMPI_LIB64" > libpath.txt

    - name: Setup MPI cygpath...
      run: |
        set /p MPIINCVAR=<includepath.txt
        set /p MPILIBVAR=<libpath.txt
        echo MPIINCVAR=%MPIINCVAR% >> %GITHUB_ENV%
        echo MPILIBVAR=%MPILIBVAR% >> %GITHUB_ENV%

    - name: choco install deps
      run: choco install winflexbison3 wget

    - name: CMake cfg
      run: >
        cmake -B build -S src
        "-DCMAKE_INSTALL_PREFIX=./install"
        -DMCVERSION="3.99.99"
        -DMCCODE_BUILD_CONDA_PKG=OFF
        -DCMAKE_INSTALL_LIBDIR=lib
        -DBUILD_MCXTRACE=ON
        -DMCCODE_USE_LEGACY_DESTINATIONS=OFF
        -DBUILD_TOOLS=ON
        -DENABLE_COMPONENTS=ON
        -DENABLE_CIF2HKL=OFF
        -DENABLE_NEUTRONICS=OFF
        -DMPIINCLUDEDIR=%MPIINCVAR%
        -DMPILIBDIR=%MPILIBVAR%

    - name: CMake build
      shell: cmd
      run: cmake --build build --config Release -j 2

    - name: CMake install
      run: cmake --install build --config Release

    - name: pip install deps
      run: pip install PyYAML ply McStasscript mslex

    - name: pip install mcpl-core preview
      run: pip install -v "git+https://github.com/mctools/mcpl@path_to_mcpl2#subdirectory=mcpl_core"

    - name: set MCXTRACE env var
      run: echo MCXTRACE=%CD%\install\share\mcxtrace\resources >> %GITHUB_ENV%

    - name: check MCXTRACE env var
      run: echo %MCXTRACE%

    - run: type .\install\share\mcxtrace\tools\Python\mccodelib\mccode_config.json
    - run: .\install\bin\mxrun -h
    - run: .\install\bin\mcxtrace -v
    - run: mcpl-config -s

    - name: Prepare rundirs
      run: mkdir run_std run_mcpl_output run_mcpl_input run_union

    - name: Prepare std instrument
      working-directory: run_std
      run: copy ..\install\share\mcxtrace\resources\examples\Tests_optics\Test_CRL.instr test.instr

    - name: Prepare MCPL_input instrument
      working-directory: run_mcpl_input
      run: |
        copy ..\install\share\mcxtrace\resources\examples\Tests_MCPL_etc\Test_MCPL_input\Test_MCPL_input.instr test.instr

    - name: Prepare MCPL_output instrument
      working-directory: run_mcpl_output
      run: copy ..\install\share\mcxtrace\resources\examples\Tests_MCPL_etc\Test_MCPL_output\Test_MCPL_output.instr test.instr

    - name: Run std instrument
      working-directory: run_std
      run: ..\install\bin\mxrun --verbose test.instr -d Single_core LENS=0

    - name: Run MCPL_output instrument
      working-directory: run_mcpl_output
      run: ..\install\bin\mxrun --verbose test.instr -d Single_core Ncount=1e3

    - name: Run MCPL_input instrument
      working-directory: run_mcpl_input
      run: ..\install\bin\mxrun --verbose test.instr -d Single_core repeat=1

    - name: Run std instrument MPI
      working-directory: run_std
      run: ..\install\bin\mxrun --verbose test.instr -d MPI_multicore -c --mpi=auto LENS=0

    # - name: Run MCPL_output instrument MPI
    #   working-directory: run_mcpl_output
    #   run: ..\install\bin\mxrun --verbose test.instr -d MPI_multicore -c --mpi=auto Ncount=1e3

    # - name: Run MCPL_input instrument MPI
    #   working-directory: run_mcpl_input
    #   run: ..\install\bin\mxrun --verbose test.instr -d MPI_multicore -c --mpi=auto repeat=1

    - name: 'Tar output files'
      id: tar-package
      if: always()
      shell: bash
      run: |
           set -e
           set -u
           set -x
           tar cvfz mcxtrace-${{ matrix.os }}_output.tgz run_*

    - name: 'Upload Artifact'
      id: tar-upload
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: output.tgz
        path: "mcxtrace-${{ matrix.os }}_output.tgz"
